graph TD
  Root --> IReactor_Multiblock[Multiblock: IReactor]
  Root --> IReactorChamber_Multiblock[Multiblock: IReactorChamber]
  Root --> IReactorComponent_Multiblock[Multiblock: IReactorComponent]
  Root --> ISteamReactorChamber_Multiblock[Multiblock: ISteamReactorChamber]
  Root --> IReactorProduct_Multiblock[Multiblock: IReactorProduct]
  Root --> IUsableUranium_Multiblock[Multiblock: IUsableUranium]
  Root --> IChamberReactor_Multiblock[Multiblock: IChamberReactor]
  Root --> IReactorPlannerComponent_Multiblock[Multiblock: IReactorPlannerComponent]
  Root --> ISteamReactor_Multiblock[Multiblock: ISteamReactor]
  Root --> FloatTracker_Multiblock[Multiblock: FloatTracker]
  Root --> SimulatedStack_Multiblock[Multiblock: SimulatedStack]
  Root --> Tracker_Multiblock[Multiblock: Tracker]
  Root --> ISimulatedReactor_Multiblock[Multiblock: ISimulatedReactor]
  Root --> BaseDurabilitySimulatedStack_Multiblock[Multiblock: BaseDurabilitySimulatedStack]
  Root --> BaseHeatSimulatedStack_Multiblock[Multiblock: BaseHeatSimulatedStack]
  Root --> FakePlayerMachine_Reactor[Reactor: FakePlayerMachine]
  Root --> IMachine_Reactor[Reactor: IMachine]
  Root --> ITerraformer_Reactor[Reactor: ITerraformer]
  Root --> ArrayTube_Reactor[Reactor: ArrayTube]
  Root --> IFluidMachine_Reactor[Reactor: IFluidMachine]
  Root --> IAnchorTile_Reactor[Reactor: IAnchorTile]
  Root --> IEnergyNet_Reactor[Reactor: IEnergyNet]
  Root --> EnergyNet_Reactor[Reactor: EnergyNet]
  Root --> APIHelper_Reactor[Reactor: APIHelper]
  Root --> IC2Classic_Reactor[Reactor: IC2Classic]
  Root --> ILocation_Reactor[Reactor: ILocation]
  Root --> DirectionList_Reactor[Reactor: DirectionList]
  Root --> LaserEvent_Reactor[Reactor: LaserEvent]
  Root --> RetextureEvent_Reactor[Reactor: RetextureEvent]
  Root --> ScrapBoxEvent_Reactor[Reactor: ScrapBoxEvent]
  Root --> FoamEvent_Reactor[Reactor: FoamEvent]
  Root --> ICutterItem_Reactor[Reactor: ICutterItem]
  Root --> ItemRegistries_Reactor[Reactor: ItemRegistries]
  Root --> ITerraformerBP_Reactor[Reactor: ITerraformerBP]
  Root --> IWrenchable_Reactor[Reactor: IWrenchable]
  Root --> PainterHelper_Reactor[Reactor: PainterHelper]
  Root --> WrenchHelper_Reactor[Reactor: WrenchHelper]
  Root --> IAdvancedComparable_Reactor[Reactor: IAdvancedComparable]
  Root --> IReactor_Reactor[Reactor: IReactor]
  Root --> IReactorChamber_Reactor[Reactor: IReactorChamber]
  Root --> IReactorComponent_Reactor[Reactor: IReactorComponent]
  Root --> ISteamReactorChamber_Reactor[Reactor: ISteamReactorChamber]
  Root --> IReactorProduct_Reactor[Reactor: IReactorProduct]
  Root --> IUsableUranium_Reactor[Reactor: IUsableUranium]
  Root --> IChamberReactor_Reactor[Reactor: IChamberReactor]
  Root --> IReactorPlannerComponent_Reactor[Reactor: IReactorPlannerComponent]
  Root --> ISteamReactor_Reactor[Reactor: ISteamReactor]
  Root --> ICropRegistry_Reactor[Reactor: ICropRegistry]
  Root --> IFarmland_Reactor[Reactor: IFarmland]
  Root --> ISubSoil_Reactor[Reactor: ISubSoil]
  Root --> ITube_Reactor[Reactor: ITube]
  Root --> TransportedItem_Reactor[Reactor: TransportedItem]
  Root --> ITeleporterTarget_Reactor[Reactor: ITeleporterTarget]
  Root --> TeleporterTarget_Reactor[Reactor: TeleporterTarget]
  Root --> IEnergyEmitter_Reactor[Reactor: IEnergyEmitter]
  Root --> IEnergyAcceptor_Reactor[Reactor: IEnergyAcceptor]
  Root --> IEnergySink_Reactor[Reactor: IEnergySink]
  Root --> LinkedSource_Reactor[Reactor: LinkedSource]
  Root --> LinkedSink_Reactor[Reactor: LinkedSink]
  Root --> IFusionRecipeList_Reactor[Reactor: IFusionRecipeList]
  Root --> SubItemInput_Reactor[Reactor: SubItemInput]
  Root --> ArrayInput_Reactor[Reactor: ArrayInput]
  Root --> FluidInput_Reactor[Reactor: FluidInput]
  Root --> IScanner_Reactor[Reactor: IScanner]
  Root --> IFluidScanner_Reactor[Reactor: IFluidScanner]
  Root --> IMiningDrill_Reactor[Reactor: IMiningDrill]
  Root --> PillarWrenchHandler_Reactor[Reactor: PillarWrenchHandler]
  Root --> StairWrenchHandler_Reactor[Reactor: StairWrenchHandler]
  Root --> ChestWrenchHandler_Reactor[Reactor: ChestWrenchHandler]
  Root --> InvertedHorizontalWrenchHandler_Reactor[Reactor: InvertedHorizontalWrenchHandler]
  Root --> HorizontalWrenchHandler_Reactor[Reactor: HorizontalWrenchHandler]
  Root --> BaseWrenchHandler_Reactor[Reactor: BaseWrenchHandler]
  Root --> HopperWrenchHandler_Reactor[Reactor: HopperWrenchHandler]
  Root --> PistonWrenchHandler_Reactor[Reactor: PistonWrenchHandler]
  Root --> ObserverBlockWrenchHandler_Reactor[Reactor: ObserverBlockWrenchHandler]
  Root --> DispenserWrenchHandler_Reactor[Reactor: DispenserWrenchHandler]
  Root --> IInputBuffer_Reactor[Reactor: IInputBuffer]
  Root --> FloatTracker_Reactor[Reactor: FloatTracker]
  Root --> SimulatedStack_Reactor[Reactor: SimulatedStack]
  Root --> Tracker_Reactor[Reactor: Tracker]
  Root --> ISimulatedReactor_Reactor[Reactor: ISimulatedReactor]
  Root --> BaseDurabilitySimulatedStack_Reactor[Reactor: BaseDurabilitySimulatedStack]
  Root --> BaseHeatSimulatedStack_Reactor[Reactor: BaseHeatSimulatedStack]
  Root --> FoamEvent_Cable[Cable: FoamEvent]
  Root --> IWrenchable_Cable[Cable: IWrenchable]
